repos:
  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: 451b56af716f9f0d0c2b816503a3fd0cf8b036fa  # frozen: v1.29.0
    hooks:
      - id: zizmor
        args: [--fix]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: 3db014c16a9d31997ab8c07a4d61fcce936c8f0d  # frozen: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]