name: Self-test zizmor reusable workflow
run-name: ${{ github.workflow }} - ${{ github.actor }} triggered self-test on ${{ github.ref_name }}

"on":
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  actions: read # Required for zizmor to analyze workflow files.

jobs:
  test-zizmor-reusable:
    uses: ./.github/workflows/zizmor.yml
    permissions:
      contents: read
      actions: read # Required for zizmor to analyze workflow files.
      security-events: write # Required to upload SARIF results to GitHub Advanced Security.
    with:
      advanced-security: false
      persona: auditor
